//! AST processing and indexing module for rustdoc JSON artifacts to SQLite.
//!
//! This module reads JSON documentation artifacts generated by `cargo doc`,
//! maps the contained symbols to a SQLite schema, and filters dependencies
//! and local crates based on the project's `Cargo.toml`.

use super::DbManager;
use anyhow::{anyhow, Result};
use cargo_toml::Manifest;
use rusqlite::params;
use rustdoc_types::{Crate, ItemEnum};
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use walkdir::WalkDir;

/// Maps `rustdoc_types::ItemEnum` variants directly to their variant string representations.
///
/// Returns `None` for internal or structural items (e.g., `StructField`) that should be skipped
/// during primary top-level indexing.
pub fn item_enum_to_kind(item_enum: &ItemEnum) -> Option<&'static str> {
    match item_enum {
        ItemEnum::Struct(_) => Some("Struct"),
        ItemEnum::Enum(_) => Some("Enum"),
        ItemEnum::Function(_) => Some("Function"),
        ItemEnum::Trait(_) => Some("Trait"),
        ItemEnum::Module(_) => Some("Module"),
        ItemEnum::TypeAlias(_) => Some("TypeAlias"),
        ItemEnum::Constant { .. } => Some("Constant"),
        ItemEnum::Static(_) => Some("Static"),
        ItemEnum::Macro(_) => Some("Macro"),
        ItemEnum::ProcMacro(_) => Some("ProcMacro"),
        ItemEnum::AssocType { .. } => Some("AssocType"),
        ItemEnum::AssocConst { .. } => Some("AssocConst"),
        ItemEnum::Variant(_) => Some("Variant"),
        ItemEnum::Impl(_) => Some("Impl"),
        ItemEnum::StructField(_) => None, // Skipped during primary indexing
        ItemEnum::Union(_) => Some("Union"),
        ItemEnum::Primitive(_) => Some("Primitive"),
        ItemEnum::ExternCrate { .. } => Some("ExternCrate"),
        ItemEnum::Use(_) => Some("Use"),
        _ => Some("Other"),
    }
}

/// Returns all supported `ItemEnum` variant names for MCP schema validation.
pub fn supported_kinds() -> Vec<&'static str> {
    vec![
        "Struct",
        "Enum",
        "Function",
        "Trait",
        "Module",
        "TypeAlias",
        "Constant",
        "Static",
        "Macro",
        "ProcMacro",
        "AssocType",
        "AssocConst",
        "Variant",
        "Impl",
        "Union",
        "Primitive",
        "ExternCrate",
        "Use",
        "Other",
    ]
}

/// Contextual metadata for the local crate and its direct dependencies extracted from `Cargo.toml`.
pub struct CrateContext {
    /// Name of the local crate (with `-` replaced by `_`).
    pub local_crate_name: Option<String>,
    /// Set of direct dependency names (with `-` replaced by `_`).
    pub direct_deps: HashSet<String>,
}

impl DbManager {
    /// Reads a rustdoc JSON file and inserts all parsed symbols into the SQLite database.
    ///
    /// This method extracts symbol types, names, full canonical paths, crate versions,
    /// and generates a unique ID formatted as `crate_name:version:id` before inserting
    /// records via a SQL transaction.
    ///
    /// # Arguments
    /// * `json_path` - Path to the `.json` rustdoc artifact to be processed.
    ///
    /// # Returns
    /// Returns `Ok(usize)` representing the total number of items indexed into the database.
    ///
    /// # Errors
    /// Returns an error if file reading fails or if SQL transaction execution encounters an issue.
    pub fn index_json_file(&mut self, json_path: &Path) -> Result<usize> {
        let content = fs::read_to_string(json_path)?;
        let raw_crate: Crate = match serde_json::from_str(&content) {
            Ok(c) => c,
            Err(_) => return Ok(0),
        };

        let file_stem = json_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown_crate");

        let crate_real_name = raw_crate
            .index
            .get(&raw_crate.root)
            .and_then(|item| item.name.as_deref())
            .unwrap_or(file_stem);

        let tx = self.conn.transaction()?;
        let mut count = 0;

        let generic_trait_methods: HashSet<&str> = [
            "clone",
            "clone_into",
            "eq",
            "ne",
            "fmt",
            "deref",
            "deref_mut",
            "drop",
            "hash",
            "from",
            "into",
            "try_from",
            "try_into",
            "as_ref",
            "borrow",
            "borrow_mut",
            "to_owned",
        ]
        .into_iter()
        .collect();

        for (id, item) in &raw_crate.index {
            let name = match &item.name {
                Some(n) if !n.is_empty() => n.as_str(),
                _ => continue,
            };

            if name.parse::<usize>().is_ok() {
                continue;
            }

            // Convert ItemEnum directly to its variant string representation
            let kind = match item_enum_to_kind(&item.inner) {
                Some(k) => k,
                None => continue,
            };

            let is_in_paths = raw_crate.paths.contains_key(id);
            let docs = item.docs.as_deref().unwrap_or("");

            if !is_in_paths && docs.is_empty() && generic_trait_methods.contains(name) {
                continue;
            }

            let full_path = if let Some(path_summary) = raw_crate.paths.get(id) {
                path_summary.path.join("::")
            } else {
                format!("{}::{}", crate_real_name, name)
            };

            // Compute Parent Path for module tree hierarchy
            let parent_path = if let Some((parent, _)) = full_path.rsplit_once("::") {
                parent.to_string()
            } else {
                crate_real_name.to_string()
            };

            let signature = format!("{:?}", item.inner);
            let crate_version = raw_crate.crate_version.as_deref().unwrap_or("0.0.0");
            let item_id = format!("{}:{}:{}", crate_real_name, crate_version, id.0);

            tx.execute(
                "INSERT OR REPLACE INTO items (id, crate_name, crate_version, kind, name, full_path, docs, signature, parent_path)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
                params![item_id, crate_real_name, crate_version, kind, name, full_path, docs, signature, parent_path],
            )?;
            count += 1;
        }

        tx.commit()?;
        Ok(count)
    }

    /// Extracts the local crate name and direct dependency list directly from `Cargo.toml`.
    ///
    /// Hyphens (`-`) in crate names are automatically converted to underscores (`_`) to align
    /// with the rustdoc JSON artifact naming convention.
    ///
    /// # Arguments
    /// * `manifest_path` - Path to the target `Cargo.toml` file.
    ///
    /// # Returns
    /// Returns a [`CrateContext`] containing the local crate name and direct dependency set.
    pub fn get_crate_context(manifest_path: &Path) -> CrateContext {
        let mut direct_deps = HashSet::new();
        let mut local_crate_name = None;

        if let Ok(manifest) = Manifest::from_path(manifest_path) {
            if let Some(package) = manifest.package {
                local_crate_name = Some(package.name.replace('-', "_"));
            }

            for (dep_name, _) in manifest.dependencies {
                direct_deps.insert(dep_name.replace('-', "_"));
            }
        }

        CrateContext {
            local_crate_name,
            direct_deps,
        }
    }

    /// Triggers automated generation of rustdoc JSON artifacts for both local crates and dependencies.
    ///
    /// Uses `cargo doc` with `RUSTC_BOOTSTRAP=1` and `RUSTDOCFLAGS="-Z unstable-options --output-format json"`
    /// to output JSON artifacts into `target/doc/` on the stable toolchain without requiring nightly.
    ///
    /// # Arguments
    /// * `manifest_path` - Path to the `Cargo.toml` file.
    ///
    /// # Errors
    /// Returns an error if the `cargo` binary cannot be located, execution fails, or the command returns
    /// a non-zero exit code.
    pub fn generate_rustdoc_json(manifest_path: &Path) -> Result<()> {
        eprintln!("[INFO] Executing 'cargo doc' to generate rustdoc JSON artifacts (local & dependencies)...");

        let abs_manifest = manifest_path
            .canonicalize()
            .unwrap_or_else(|_| manifest_path.to_path_buf());

        let project_dir = abs_manifest
            .parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));

        let cargo_bin = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());

        let output = Command::new(cargo_bin)
            .current_dir(&project_dir)
            .env("RUSTC_BOOTSTRAP", "1")
            .env("RUSTDOCFLAGS", "-Z unstable-options --output-format json")
            .arg("doc")
            .arg("--manifest-path")
            .arg(&abs_manifest)
            .output()?;

        if output.status.success() {
            eprintln!("[SUCCESS] Successfully generated rustdoc JSON artifacts!");
            Ok(())
        } else {
            let stderr_msg = String::from_utf8_lossy(&output.stderr);
            eprintln!(
                "[ERROR] Command 'cargo doc' failed to execute:\n{}",
                stderr_msg
            );
            Err(anyhow!(
                "Failed to execute automated 'cargo doc': {}",
                stderr_msg.trim()
            ))
        }
    }

    /// Scans the target documentation directory and indexes relevant JSON files into SQLite.
    ///
    /// Checks for the presence of the local crate's JSON artifact. If missing, it automatically triggers
    /// [`generate_rustdoc_json`](Self::generate_rustdoc_json). Only JSON files matching the local crate
    /// or direct dependencies are indexed. Local crates are re-indexed incrementally on changes,
    /// while external dependencies are indexed once upon first encounter.
    ///
    /// # Arguments
    /// * `target_dir` - Path to the target doc directory (e.g., `"target/doc"`).
    /// * `manifest_path` - Path to the `Cargo.toml` file.
    ///
    /// # Errors
    /// Returns an error if SQLite query failures or directory I/O issues occur.
    pub fn scan_and_index_target(&mut self, target_dir: &Path, manifest_path: &Path) -> Result<()> {
        let ctx = Self::get_crate_context(manifest_path);

        // 1. Check if local crate JSON artifact already exists
        let local_json_exists = if let Some(ref local_name) = ctx.local_crate_name {
            target_dir.join(format!("{}.json", local_name)).exists()
        } else {
            false
        };

        // 2. Trigger auto-generation if local artifact is missing
        if !local_json_exists {
            if let Err(e) = Self::generate_rustdoc_json(manifest_path) {
                eprintln!("[WARNING] Failed to generate rustdoc JSON artifacts: {}", e);
            }
        }

        if !target_dir.exists() {
            return Ok(());
        }

        for entry in WalkDir::new(target_dir).into_iter().filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("json") {
                let file_stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");

                let is_local_crate = ctx
                    .local_crate_name
                    .as_ref()
                    .map_or(false, |name| name == file_stem);

                let is_direct_dep = ctx.direct_deps.contains(file_stem);

                if is_local_crate || is_direct_dep {
                    // Local crate is always re-indexed to incorporate code changes.
                    // External dependencies are indexed only if not already present in DB.
                    if is_local_crate {
                        let _ = self.index_json_file(path);
                    } else {
                        let exists: bool = self
                            .conn
                            .query_row(
                                "SELECT EXISTS(SELECT 1 FROM items WHERE crate_name = ?1)",
                                [file_stem],
                                |row| row.get(0),
                            )
                            .unwrap_or(false);

                        if !exists {
                            let _ = self.index_json_file(path);
                        }
                    }
                }
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_generate_rustdoc_json() {
        let manifest_path = PathBuf::from("Cargo.toml");
        let result = DbManager::generate_rustdoc_json(&manifest_path);
        assert!(
            result.is_ok(),
            "Failed to generate rustdoc JSON: {:?}",
            result.err()
        );
    }
}
